services:
    TheoVauvilliers\GridBundle\Factory\GridDefinitionFactory:
        arguments:
            - '@TheoVauvilliers\GridBundle\Provider\GridDefinitionProvider'
            - '@serializer'

    TheoVauvilliers\GridBundle\Factory\GridQueryBuilderFactory:
        arguments:
            - '@doctrine.orm.entity_manager'
